auth:
  username: shopuser
  database: shopdb

primary:
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  extendedConfiguration: |
    max_connections = 400
    shared_buffers = 128MB
    effective_cache_size = 512MB
